spring:
  application:
    name: FitnessTrackerBackend

  flyway:
    enabled: true
    create-schemas: true
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?currentSchema=fitnesstracker
#    user: ${POSTGRES_USER_ADMIN:${POSTGRES_USER}}
#    password: ${POSTGRES_PASSWORD_ADMIN:${POSTGRES_PASSWORD}}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    placeholders:
      flyway_admin_password: ${POSTGRES_PASSWORD_ADMIN}
      flyway_trainer_password: ${POSTGRES_PASSWORD_TRAINER}
      flyway_trainee_password: ${POSTGRES_PASSWORD_TRAINEE}
    validate-on-migrate: true
    schemas: fitnesstracker
    default-schema: fitnesstracker

  datasource:
    admin:
      jdbc-url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?currentSchema=fitnesstracker
      username: ${POSTGRES_USER_ADMIN:${POSTGRES_USER}}
      password: ${POSTGRES_PASSWORD_ADMIN:${POSTGRES_PASSWORD}}
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: AdminPool
        minimum-idle: 1
        maximum-pool-size: 5

    trainer:
      jdbc-url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?currentSchema=fitnesstracker
      username: ${POSTGRES_USER_TRAINER:${POSTGRES_USER}}
      password: ${POSTGRES_PASSWORD_TRAINER:${POSTGRES_PASSWORD}}
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: TrainerPool
        minimum-idle: 2
        maximum-pool-size: 10

    trainee:
      jdbc-url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?currentSchema=fitnesstracker
      username: ${POSTGRES_USER_TRAINEE:${POSTGRES_USER}}
      password: ${POSTGRES_PASSWORD_TRAINEE:${POSTGRES_PASSWORD}}
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: TraineePool
        minimum-idle: 5
        maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: fitnesstracker
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:80}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}